project:
  type: website
  output-dir: docs

website:
  title: "Statistics, plain and sample"
  site-url: "https://gjkerns.github.io"
  twitter-card: 
    creator: "@gkerns"
  open-graph: true
  page-footer: "Copyright 2022, G. Jay Kerns"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gjkerns
      - icon: linkedin
        href: https://www.linkedin.com/in/g-jay-kerns-9ab99111/
      - icon: mastodon
        href: "https://mathstodon.xyz/@gjkerns"
format:
  html:
    theme: 
      light: simplex
      dark: darkly
    css: styles.css

editor: visual

