project:
  type: website
  output-dir: docs

website:
  title: "Statistics, plain and sample"
  site-url: "https://gjkerns.github.io"
  description: "Statistics, plain and sample."
  favicon: favicon.ico
#  twitter-card: true
  open-graph: true
  page-footer: "Copyright 2022, G. Jay Kerns"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: person
        href: https://gkerns.people.ysu.edu
      - icon: github
        href: https://github.com/gjkerns
      - icon: mastodon
        href: 'https://mathstodon.xyz/@gjkerns'
      - icon: linkedin
        href: https://www.linkedin.com/in/g-jay-kerns-9ab99111/
format:
  html:
    theme: 
      light: simplex
      dark: darkly
    css: styles.css

editor: visual

